### ISSUE TITLE
Defeito ao executar deploy.sh

### ISSUE THREAD

**Issue by renanleonellocastro** [victorshinya/website-base#1]
Fala victor,

Eu estou tentando executar o deploy.sh para subir a aplicação node.js para a cloud, porém, como ainda não tenho o cloud foundry api configurado, apresenta o seguinte erro:
`notebook:/home/renan/Desktop/Linux/ibm/site # ./deploy.sh`
`FAILED
No CF API endpoint set. Use 'ibmcloud target --cf' to target a CloudFoundry environment.`

Basicamente eu precisei executar o seguinte comando para adicionar a referência do cloud foundry, mas não sei se era esse mesmo o jeito correto. A partir disso, o deploy.sh passou a funcionar.

`ibmcloud target --cf-api https://api.us-east.bluemix.net`

Agora estou seguindo o Get Started da SDK Node.js do ibm cloud. Lá ele está explicando no item 2 como criar uma organização e um espaço no Cloud Foundry.

https://cloud.ibm.com/docs/account/orgs_spaces.html?locale=pt

**Comment by victorshinya** [comment]
@renanleonellocastro é isso mesmo. Antes de fazer o deploy, você tem que executar dois comandos:

`ibmcloud login` e `ibmcloud target --cf` (add -api + API URL caso você vá fazer o deploy em outra `region` que não seja Dallas/US-South).

Assim que ambos os comandos rodarem, você conseguirá fazer o deploy na sua conta 100%

**Comment by renanleonellocastro** [comment]
Beleza Victor. Obrigado!
